# Generated by Django 5.1.2 on 2024-10-16 05:50

import src.domain.beats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платный/по подписке')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Счетчик использования')),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество лайков')),
                ('file', models.FileField(blank=True, null=True, upload_to=src.domain.beats.models.Beat.upload_to, verbose_name='Файл')),
                ('preview', models.FileField(blank=True, null=True, upload_to=src.domain.beats.models.Beat.upload_to, verbose_name='Превью')),
                ('image', models.ImageField(blank=True, null=True, upload_to=src.domain.beats.models.Beat.upload_to, verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(related_name='beats', to='beats.category', verbose_name='Категории')),
                ('tags', models.ManyToManyField(related_name='beats', to='beats.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Бит',
                'verbose_name_plural': 'Биты',
                'ordering': ('order',),
            },
        ),
    ]
