# Generated by Django 5.1.2 on 2025-01-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Скрыть"),
        ),
        migrations.AlterField(
            model_name="beat",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="beat",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="beats", to="beats.tag", verbose_name="Теги"
            ),
        ),
    ]
